### ISSUE TITLE
CR: Update Footer social media title "Twitter" to "X"

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-ca#46] opened 2023-10-19 15:44 UTC
Description
Since Twitter is now called X, the footer's social media title "Twitter" next to the icon must be replaced with the new "X" on both the USA and Canadian Volvo global footers

Acceptance Criteria
 1. The Twitter title on the footer is replaced by the new X title

Image
![Image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/2ad55466-83ba-4f3c-8cf3-8c15ae1b8b3e)

Notes
[Font Awesome x-twitter Icon](https://fontawesome.com/icons/x-twitter?f=brands&s=solid)

**Comment by ZoeBeykirch** [comment] 2023-10-19 15:46
@manuel-vara I wanted to create this ticket for the Volvo US site, but am still not able to access it. I know you had shared an update that I'm on the repo, but for some reason it's still not in my drop down list when creating new issues.

**Comment by BeckyMedlin** [comment] 2023-11-03 15:43
This CR can wait until all other necessary migration work is completed.

**Comment by BeckyMedlin** [comment] 2023-11-03 15:44
@Gonzalo-CG Please add the enhancement label. I'm not able to edit this one for some reason.

**Comment by ZoeBeykirch** [comment] 2023-12-08 20:22
Suggest assigning this ticket to the same developer who can work on issue https://github.com/hlxsites/vg-volvotrucks-us/issues/507 in the same sprint so we can push an update to the footer once instead of twice.

**Comment by BeckyMedlin** [comment] 2024-01-11 19:51
@Gonzalo-CG This appears to be a duplicate of https://github.com/hlxsites/vg-volvotrucks-us/issues/487  
 Please add the link @ZoeBeykirch noted in her comment on Dec. 8 to #487 and let's close this one.

**Comment by Kannan-CM** [comment] 2024-04-18 12:50
This is already completed not Contnet task

**Closed by Kannan-CM** 2024-04-18 12:50 UTC
Labels: enhancement, Content
